# -*- coding: utf-8 -*-
"""DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCGgDevufHB6pC1u4tPfo7bRyv81k84v

##DataFrame
"""

import pandas as pd ## pd alis, adopta el valor de la libreria pandas.

"""#Crear un Diccionario
## Tipo de objeto en python para crear un set de datos en formato tabla.
"""

Data = { 'Estudiante': [1, 2, 3, 4, 5],
            'Edad': [20, 30, 40, 50, 60],
             'Nombre': ['Juan', 'Ana','Cristian', 'Maria', 'Carlos'],
              'Apellido': ['Lopez', 'Marin', 'Diaz', 'Carlos', 'Aladana'] }

"""## Crear un Directorio a partir del diccionario Data"""

pd.DataFrame(Data)